### ISSUE TITLE
Does refreshing the slots page over and over really work?

### ISSUE THREAD

**Issue by dougwebb** [mark-thompson/whole-foods-deliverance#21]
I would expect that it doesn't work, and that Amazon would intentionally disable it to discourage the use of scripts like this. I've modified run.py line 140 to replace `driver.refresh()` with `build_route(site_config, 'SLOT_SELECT').navigate(driver)` to replicate what a person might do when retrying. I'll run that for a while and see if it works any better. (Several hours with just the refresh didn't get me any slots.)

This might be a good command-line option to provide, to choose the refresh mode.

**Comment by dougwebb** [comment]
I should also add that, when doing this manually, going through the cart page every time also alerted me to items getting dropped from my cart. You could provide that alert too, by keeping track of the # of items in the cart and the total price. I've seen the price change without the # items changing; that's worth an alert but I wouldn't interrupt the script unless it's a large increase.

**Comment by mark-thompson** [comment]
Unless something has changed drastically since yesterday, refreshing the page appears to query slot availability data and will detect new slots when released.

Interesting idea, though. I've thought about adding the ability to track cart state, even if it just means keeping track of the items that appear in the OOS alert

**Comment by dougwebb** [comment]
I guess I'll switch back to just refreshing then. I had no luck today running it my way either, and your way is at least more efficient.

**Comment by dougwebb** [comment]
Well, that didn't take long. I just got an order scheduled! Thanks!
I have another request, but I'll add a new issue for it.
