### ISSUE TITLE
Handle throttle.html page

### ISSUE THREAD

**Issue by dougwebb** [mark-thompson/whole-foods-deliverance#22]
This page is pretty rare, but I've seen it now and then while trying to check out manually, and I just saw it twice while running the script:

[2020-04-14 11:33:48] {navigate} WARNING: Current URL 'https://www.amazon.com/gp/buy/error/handlers/throttle.html' does not match target         
Handling possible redirect (timeout in 30s)                                                                                                      
[2020-04-14 11:34:18] {navigate} ERROR: Timed out waiting for redirect to a valid dest                                                           
Current URL: 'https://www.amazon.com/gp/cart/view.html'                                                                                          

The challenge is that the page contains a button that's disabled initially, with a progress bar. It takes 20sec or so and then turns into an active button that takes you back to the cart page.

Once it's active, the source looks like this:

```html
<a id="checkout-throttle-return-to-cart-announce" href="https://www.amazon.com/gp/cart/view.html" class="a-button-text" role="button">
      Continue
    </a>
```

**Comment by mark-thompson** [comment]
Thanks for the source! I hadn't encountered that one yet. 
To clarify, were you also seeing this before changing the refresh to the full slot select navigation sequence (thus increasing your page loads by 5x)?
If you encounter it again, could you also provide the source before it's active? It wouldn't be too hard to handle this assuming I can reliably identify it and wait for it to be active/clickable

**Comment by dougwebb** [comment]
This happened while I was doing the full navigation sequence. I didn't see exactly when it happened, but based on the second log message I'd guess that it had waited after seeing no slots, navigated to the main page, and then clicked to view the cart and got the throttle instead. If that's where they've inserted the throttle, then it makes sense that you haven't seen it if you're just refreshing the slots page.

It's possible that Amazon was throttling me specifically because of the number of requests I was sending. I hadn't thought of that; my impression was that this was a system-wide throttle based on their overall load. I have no evidence either way.

**Comment by benholtz** [comment]
I've seen this too during busy times when refreshing manually, its definitely on the checkout page load where you would see what slots are avail.

**Comment by mark-thompson** [comment]
@dougwebb @benholtz Just added a handler for this. Tested on the source provided above, but haven't been able to test in the wild.
The source will be dumped when that page is encountered, regardless of `--debug`, so please upload here if you have issues

**Comment by mark-thompson** [comment]
Closing this for now
