### ISSUE TITLE
Chrome being controlled by automated software

### ISSUE THREAD

**Issue by makrandp** [mark-thompson/whole-foods-deliverance#25]
My chrome is still showing that Chrome being controlled by automated software. Even though i am not using the software now. 
Had to reinstall chrome to fix the issue.
Is there something I missed? How can I avoid this next time?

**Comment by makrandp** [comment]
Also, whenever i was clicking on any URL, it was opening a new chrome window with the same message on top.

**Comment by mark-thompson** [comment]
I've run into this before - it only seems to happen if you close all tabs in your normal browser session while the Selenium `chromedriver` browser session is still active.
Ensuring all instances of the Chrome app/executable are closed before attempting to launch again should be sufficient to prevent this.
