### ISSUE TITLE
Add Amazon Fresh compatibility

### ISSUE THREAD

**Issue by mark-thompson** [mark-thompson/whole-foods-deliverance#6]
This may be as simple as adding additional site config / routes in `config.py`

**Comment by steezJ** [comment]
I think it is. I changed it to look for 'Checkout Amazon Fresh Cart' and it gets to the check out page.

**Comment by mark-thompson** [comment]
@steezJ Were you actually able to complete the checkout process or did you just make it to the slot select page? I haven't been able to find an open slot in the limited bit of testing I've done

**Comment by ChakChak1234** [comment]
> @steezJ Were you actually able to complete the checkout process or did you just make it to the slot select page? I haven't been able to find an open slot in the limited bit of testing I've done

I think this is the part where selenium has to auto refresh every hour or so and look for open slots. I'm stuck at this part because I can't define the elements if I've never seen it.
