### ISSUE TITLE
question rather than issue

### ISSUE THREAD

**Issue by ffcode2020** [mark-thompson/whole-foods-deliverance#8]
first of all great concept and execution ! the code runs fine on python 3.7

In amazon final screen, it says select a day : Today or Tomorrow.

does the code check windows only for today ? most likely Tomorrow has more chances to have openings so I'd like the code to check both days. Is this the case ?

**Comment by mark-thompson** [comment]
Thanks! That is indeed the case. You can also specify which days / slot times you're interested in via the config: `conf.toml`
